language: node_js
node_js:
- '8'
sudo: required
env:
- CXX=g++-4.9
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
script:
- node ./dist/index.js &
- node ./postman/test.js
deploy:
  provider: heroku
  app: hypercontract
  api_key:
    secure: lS5mn+2H6VkfBLQkqj/WiNrgntRTuh9vjXmBtvqZzljYP2aZz94nkQm1/zjaLzjgVomYncXLaOYh6bK0FH5cLLKeM/IfG8w1yOEDpADVUBgsRBu52ZZMQriEORJCHXnzwusGrl5dIXW+FUIUqocd7hubX1hxQiBZCzUnEoX2rifDou0YuWXDg2kMrXlwHdX0owVdl/7AWVxABYS3bvzXRMOGVairHIh294GQT3nWD6JL2JPuajCwQUwNmUfub2cZ37j7BOURfmMQIxfG0nLAqL6FvByFhVnNwUTaw1+G4CdFamwDZEr1BUqP4s79l6UTCZFapYR6HflPZv9JwkoXHDaaQMjSTbuFxWj+HjXocAxFMZiUl/MOPNMkpVYWnT3EbwGCmusZ9qw4DeMa+qj/yspmFpNXrCv2QpbYrpJQyHjhLZZpSvkPiSspgbYjOZYde+jAu7ug18/vldXljs3mt3UGMEfUwXz/FR45fMzdPERowiFnf1Q0kPNqOTSJdWmOrizrqgcmdkv2geRxtbMRBFdzpuvFgiSeGZnxSxTrNo4MN+UU7qHE3FPPMYhpO76ELv9MnmzoNuSdH/cdgzy07EwtfTMFBLQ2ine/jLkEv7lA0IS2v3JlFiDD7zVDzBf8FH8xVZGI1C8UUEIhDmU1uMJAGzi4CU6y4pE4cDOjV+Q=
