pool:
  name: Hosted Ubuntu 1604
  demands: npm

steps:
- task: YodLabs.VariableTasks.SetVariableFromJSON.SetValueFromJSON@0
  displayName: 'Read version from package.json'
  inputs:
    variableName: application.version
    jsonPathExpression: '$.version'
    jsonFile: package.json

- task: YodLabs.VariableTasks.SetVariable.SetVariable@0
  displayName: 'Set application.buildName'
  inputs:
    variableName: application.buildName
    value: '$(application.version)-$(Build.BuildNumber)'

- task: Npm@1
  displayName: 'npm ci'
  inputs:
    command: custom
    verbose: false
    customCommand: ci

- task: Npm@1
  displayName: 'npm run ci-test'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run ci-test'

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFiles: junit.xml

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'

- task: FileTransform@1
  displayName: 'Write version to configuration'
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)'
    fileType: json
    targetFiles: config/default.json

- task: Npm@1
  displayName: 'npm run ci-build'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run ci-build'

- task: Docker@2
  displayName: 'Build image and push to ACR'
  inputs:
    containerRegistry: 'ACR'
    repository: 'hypercontract/hypercontract'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest
      $(application.buildName)
